### ISSUE TITLE
Search example

### ISSUE THREAD

**Issue by kipergil** [stellar-admin/issues#1]
Hey guys, great work.
Just started experimenting and this is exactly what i needed.
It would be nice to add a basic search example in the samples.
Thanks

**Comment by jerriep** [comment]
Thank you for the comment @kipergil .

Search is not currently supported in the framework, but it is high on the list of features to add. I will notify you once it is available

**Comment by jerriep** [comment]
@kipergil v0.15 which I just published to NuGet supports search. Adding search to a resource definition involves 2 steps:

1. Enable search in the constructor of the resource definition:
  https://github.com/stellar-admin/samples/blob/83982634c8de82bc70df4b77ccd110a8781f7a09/Store/Stellar/Resources/CustomerDefinition.cs#L18

2. Apply the search term by overriding the `ApplySearchFilter` method (when using EF):
  https://github.com/stellar-admin/samples/blob/83982634c8de82bc70df4b77ccd110a8781f7a09/Store/Stellar/Resources/CustomerDefinition.cs#L24-L33

    or apply the search in the `GetListAsync` method when using a custom data source:
    https://github.com/stellar-admin/samples/blob/07fb0104a7fcf98807e2490196d28d93877499f4/ContactList/Stellar/Resources/ContactDefinition.cs#L64-L69

Let me know if you have other questions or suggestions
